name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create environment.prod.ts
        run: |
          mkdir -p src/environments
          echo "export const environment = {" > src/environments/environment.prod.ts
          echo "  production: true," >> src/environments/environment.prod.ts
          echo "  firebaseApiKey: '${{ secrets.FIREBASE_API_KEY }}'," >> src/environments/environment.prod.ts
          echo "};" >> src/environments/environment.prod.ts

      - name: Create environment.ts
        run: |
          echo "export const environment = {" > src/environments/environment.ts
          echo "  production: false," >> src/environments/environment.ts
          echo "  firebaseApiKey: 'your-api-key-for-development'," >> src/environments/environment.ts
          echo "};" >> src/environments/environment.ts
      
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MONEYTRACKER_D40D1 }}
          channelId: live
          projectId: moneytracker-d40d1
